export default {
  data() {
    return {
      sessions: [
        {
          issue: 'Registration',
          time: '09:00 - 10:00',
        },
        { divider: true },
        {
          issue: 'Opening Ceremony',
          time: '10:00 - 10:25',
          venue: 'LT 17',
        },
        { divider: true },
        {
          title: 'Ecosystem of IT industry',
          speaker: 'Wan Leung Wong',
          icon: '/2017/img/speaker/wanleung.jpg',
          venue: 'LT 17',
          time: '10:25 - 11:10',
          link: '/topic/ecosystem',
        },
        { divider: true },
        {
          title: 'Data Science and Engineering in Internet Media',
          speaker: 'Dick Tang',
          icon: '/2017/img/speaker/unknown.png',
          venue: 'LT 17',
          time: '11:20 - 12:05',
          link: '/topic/media',
        },
        {
          title: 'Essential Blockchain Knowledge for Bitcoin Investment',
          speaker: 'Johnny Chiu',
          icon: '/2017/img/speaker/johnny.jpg',
          venue: 'LT 18',
          time: '11:20 - 12:05',
          link: '/topic/blockchain',
        },
        { divider: true },
        {
          title: 'Transferring Painlessly from Web to Mobile Apps with React Native',
          speaker: 'Rachel',
          icon: '/2017/img/speaker/rachel.jpg',
          venue: 'LT 17',
          time: '12:15 - 13:00',
          link: '/topic/react-native',
        },
        {
          title: 'The Geek - Rock with Sanity in this Tech Gold Rush',
          speaker: 'Clara Chau',
          icon: '/2017/img/speaker/clara.jpg',
          venue: 'LT 18',
          time: '12:15 - 13:00',
          link: '/topic/the-geek',
        },
        { divider: true },
        {
          issue: 'Lunch',
          time: '13:00 - 14:30',
        },
        { divider: true },
        {
          title: 'A Glimpse of Data Science and How to Kick-start Your Cloud Career',
          speaker: '(TBD)',
          icon: '/2017/img/speaker/unknown.png',
          venue: 'LT 17',
          time: '14:30 - 15:30',
          link: '/topic/ds',
        },
        { divider: true },
        {
          title: 'Play Python around with Jupyter',
          speaker: 'Wong Ho Wa',
          icon: '/2017/img/speaker/unknown.png',
          venue: 'LT 17',
          time: '15:45 - 16:30',
          link: '/topic/jupyter',
        },
        {
          title: 'Discussion on cultural differences between Easterners & Westerners',
          speaker: 'Gary Kwong',
          icon: '/2017/img/speaker/gary.jpg',
          venue: 'LT 18',
          time: '15:45 - 16:30',
          link: '/topic/culture-differences',
        },
        { divider: true },
        {
          title: 'Electronic tools for science - how I ended up building gear for atomic physics in Hong Kong',
          speaker: 'Sébastien Bourdeauducq',
          icon: '/2017/img/speaker/sebastien.png',
          venue: 'LT 17',
          time: '16:45 - 17:30',
          link: '/topic/electronic',
        },
        {
          title: 'Welcome the Brand New Ruby-like Language - Goby',
          speaker: 'Maxwell',
          icon: '/2017/img/speaker/maxwell.jpg',
          venue: 'LT 18',
          time: '16:45 - 17:30',
          link: '/topic/goby',
        },
        { divider: true },
        {
          issue: 'Lightning Talk',
          venue: 'LT 17',
          time: '17:45 - 18:00',
        },
        { divider: true },
        {
          issue: 'Closing Ceremony',
          venue: 'LT 18',
          time: '18:00 - 18:30',
        },
      ],
    };
  },
};
